; Installer and uninstaller strings (generated from the Chinese originals).
; The installer language is chosen in the language dialog (preselected from the settings or
; Windows language; English for languages other than Chinese); see zhiyi-setup.nsi.

LangString L_001 ${LANG_ENGLISH} "Open Zhiyi IME settings"
LangString L_001 ${LANG_SIMPCHINESE} "启动知意输入法设置"
LangString L_002 ${LANG_ENGLISH} "Zhiyi IME has been uninstalled. A few program files are still in use and will be removed when Windows restarts. Restart now or later?"
LangString L_002 ${LANG_SIMPCHINESE} "知意输入法已卸载。少量程序文件仍在使用中，将在重新启动 Windows 后自动删除。要现在重新启动吗？"
LangString L_003 ${LANG_ENGLISH} "Could not confirm that the Zhiyi IME service has stopped; files were not overwritten."
LangString L_003 ${LANG_SIMPCHINESE} "无法确认知意输入法后台已终止，未继续覆盖文件。"
LangString L_004 ${LANG_ENGLISH} "Could not safely recover the previous unfinished Zhiyi IME installation."
LangString L_004 ${LANG_SIMPCHINESE} "无法安全恢复上一次未完成的知意输入法安装。"
LangString L_005 ${LANG_ENGLISH} "The Zhiyi IME update folder still contains files from an unfinished installation."
LangString L_005 ${LANG_SIMPCHINESE} "知意输入法更新目录中仍有未完成的安装文件。"
LangString L_006 ${LANG_ENGLISH} "Could not create the Zhiyi IME update folder."
LangString L_006 ${LANG_SIMPCHINESE} "无法创建知意输入法更新目录。"
LangString L_007 ${LANG_ENGLISH} "Could not extract the Zhiyi IME installation files."
LangString L_007 ${LANG_SIMPCHINESE} "无法解压知意输入法安装文件。"
LangString L_008 ${LANG_ENGLISH} "Could not activate the new Zhiyi IME files."
LangString L_008 ${LANG_SIMPCHINESE} "无法启用新的知意输入法文件。"
LangString L_009 ${LANG_ENGLISH} "The installation was committed, but its transaction marker could not be deleted."
LangString L_009 ${LANG_SIMPCHINESE} "安装状态已提交，但未能删除安装事务标记。"
LangString L_010 ${LANG_ENGLISH} "Zhiyi IME ${VERSION} is installed, but the system IME module could not be updated.$\r$\n$\r$\n$FailureMessage$\r$\n$\r$\nThe installation state was kept; running the installer again will retry."
LangString L_010 ${LANG_SIMPCHINESE} "知意输入法 ${VERSION} 已安装，但系统 IME 模块未能完成更新。$\r$\n$\r$\n$FailureMessage$\r$\n$\r$\n安装状态已保留，后续运行安装程序时会再次尝试。"
LangString L_011 ${LANG_ENGLISH} "Zhiyi IME ${VERSION} has been installed."
LangString L_011 ${LANG_SIMPCHINESE} "知意输入法 ${VERSION} 安装已完成。"
LangString L_012 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nCould not clean up the staging folder; the service was not restarted."
LangString L_012 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n无法清理安装暂存目录，未恢复启动后台。"
LangString L_013 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe Zhiyi IME service could not be restarted automatically. Check the processes using it or start Zhiyi IME manually."
LangString L_013 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n知意输入法后台未能自动恢复，请检查占用进程或手动启动知意输入法。"
LangString L_014 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe installed Zhiyi IME files were not changed."
LangString L_014 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n已安装的知意输入法文件未发生变化。"
LangString L_015 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe automatic rollback did not finish. Run the installer again before using Zhiyi IME."
LangString L_015 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n自动回滚未能完成。请重新运行安装程序后再使用知意输入法。"
LangString L_016 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nZhiyi IME was restored to its state before the installation."
LangString L_016 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n已恢复知意输入法安装前的状态。"
LangString L_017 ${LANG_ENGLISH} "The Zhiyi IME service is still exiting; its program files will be removed after Windows restarts."
LangString L_017 ${LANG_SIMPCHINESE} "知意输入法后台仍在退出；相关程序文件将在 Windows 重启后删除。"
LangString L_018 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe automatic rollback did not finish. Run the uninstaller again before using Zhiyi IME."
LangString L_018 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n自动回滚未能完成。请重新运行卸载程序后再使用知意输入法。"
LangString L_019 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nZhiyi IME was restored to its state before the uninstallation."
LangString L_019 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n已恢复卸载前的知意输入法状态。"
LangString L_020 ${LANG_ENGLISH} "Could not delete the Zhiyi IME uninstall registry key. Run the uninstaller again."
LangString L_020 ${LANG_SIMPCHINESE} "无法删除知意输入法卸载注册表项。请重新运行卸载程序。"
LangString L_021 ${LANG_ENGLISH} "Could not delete the Zhiyi IME startup registry key. Run the uninstaller again."
LangString L_021 ${LANG_SIMPCHINESE} "无法删除知意输入法启动注册表项。请重新运行卸载程序。"
LangString L_022 ${LANG_ENGLISH} "Zhiyi IME"
LangString L_022 ${LANG_SIMPCHINESE} "知意输入法"
LangString L_023 ${LANG_ENGLISH} "Could not read the Zhiyi IME service state before installation."
LangString L_023 ${LANG_SIMPCHINESE} "无法读取知意输入法安装前后台状态。"
LangString L_024 ${LANG_ENGLISH} "Could not read the Zhiyi IME service process ID."
LangString L_024 ${LANG_SIMPCHINESE} "无法读取知意输入法后台进程标识。"
LangString L_025 ${LANG_ENGLISH} "The Zhiyi IME service has been restarted."
LangString L_025 ${LANG_SIMPCHINESE} "知意输入法后台已恢复启动。"
LangString L_026 ${LANG_ENGLISH} "The Zhiyi IME service could not be restarted."
LangString L_026 ${LANG_SIMPCHINESE} "知意输入法后台恢复启动失败。"
LangString L_027 ${LANG_ENGLISH} "Could not confirm that the new Zhiyi IME service has started."
LangString L_027 ${LANG_SIMPCHINESE} "无法确认新版本知意输入法后台已启动。"
LangString L_028 ${LANG_ENGLISH} "The Zhiyi IME TSF release request failed; checking file locks."
LangString L_028 ${LANG_SIMPCHINESE} "知意输入法 TSF 释放请求失败，继续检查文件占用。"
LangString L_029 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe restored pre-installation state of Zhiyi IME failed verification; the service was not started."
LangString L_029 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n知意输入法安装前状态未通过恢复校验，未启动后台。"
LangString L_030 ${LANG_ENGLISH} "Windows could not list the applications that are using Zhiyi IME."
LangString L_030 ${LANG_SIMPCHINESE} "Windows 无法提供正在使用知意输入法的应用程序详情。"
LangString L_031 ${LANG_ENGLISH} "Could not read which applications use the previous version; continuing."
LangString L_031 ${LANG_SIMPCHINESE} "无法读取旧版本文件占用信息，安装继续。"
LangString L_032 ${LANG_ENGLISH} "Checking which applications use the previous version timed out; continuing."
LangString L_032 ${LANG_SIMPCHINESE} "检查旧版本文件占用超时，安装继续。"
LangString L_033 ${LANG_ENGLISH} "The previous Zhiyi IME installation transaction is incomplete or invalid."
LangString L_033 ${LANG_SIMPCHINESE} "先前的知意输入法安装事务不完整或无效。"
LangString L_034 ${LANG_ENGLISH} "Could not unregister the 32-bit TSF module left by an interrupted installation."
LangString L_034 ${LANG_SIMPCHINESE} "无法注销中断安装留下的 32 位 TSF 模块。"
LangString L_035 ${LANG_ENGLISH} "Could not unregister the 64-bit TSF module left by an interrupted installation."
LangString L_035 ${LANG_SIMPCHINESE} "无法注销中断安装留下的 64 位 TSF 模块。"
LangString L_036 ${LANG_ENGLISH} "The previous Zhiyi IME installation state was restored."
LangString L_036 ${LANG_SIMPCHINESE} "已恢复先前的知意输入法安装状态。"
LangString L_037 ${LANG_ENGLISH} "Could not restore the previous Zhiyi IME program files."
LangString L_037 ${LANG_SIMPCHINESE} "无法恢复先前的知意输入法程序文件。"
LangString L_038 ${LANG_ENGLISH} "The previous Zhiyi IME uninstallation did not finish. Run the installed uninstaller again first."
LangString L_038 ${LANG_SIMPCHINESE} "上一次知意输入法卸载尚未完成。请先重新运行已安装的卸载程序。"
LangString L_039 ${LANG_ENGLISH} "Could not clean up the Zhiyi IME files left by a completed installation."
LangString L_039 ${LANG_SIMPCHINESE} "无法清理已完成安装留下的知意输入法文件。"
LangString L_040 ${LANG_ENGLISH} "Could not write the Zhiyi IME installation transaction."
LangString L_040 ${LANG_SIMPCHINESE} "无法写入知意输入法安装事务。"
LangString L_041 ${LANG_ENGLISH} "Could not commit the Zhiyi IME installation transaction (Win32 error $1)."
LangString L_041 ${LANG_SIMPCHINESE} "无法提交知意输入法安装事务（Win32 错误 $1）。"
LangString L_042 ${LANG_ENGLISH} "Could not record the Zhiyi IME system IME update state."
LangString L_042 ${LANG_SIMPCHINESE} "无法记录知意输入法系统 IME 更新状态。"
LangString L_043 ${LANG_ENGLISH} "Could not complete the Zhiyi IME system IME update state."
LangString L_043 ${LANG_SIMPCHINESE} "无法完成知意输入法系统 IME 更新状态。"
LangString L_044 ${LANG_ENGLISH} "Could not install the 64-bit legacy IME module."
LangString L_044 ${LANG_SIMPCHINESE} "无法安装 64 位传统 IME 模块。"
LangString L_045 ${LANG_ENGLISH} "Could not install the 32-bit legacy IME module."
LangString L_045 ${LANG_SIMPCHINESE} "无法安装 32 位传统 IME 模块。"
LangString L_046 ${LANG_ENGLISH} "Could not register the 64-bit TSF module."
LangString L_046 ${LANG_SIMPCHINESE} "无法注册 64 位 TSF 模块。"
LangString L_047 ${LANG_ENGLISH} "Could not register the 32-bit TSF module."
LangString L_047 ${LANG_SIMPCHINESE} "无法注册 32 位 TSF 模块。"
LangString L_048 ${LANG_ENGLISH} "Could not restore the previous 64-bit TSF registration."
LangString L_048 ${LANG_SIMPCHINESE} "无法恢复先前的 64 位 TSF 注册。"
LangString L_049 ${LANG_ENGLISH} "Could not restore the previous 32-bit TSF registration."
LangString L_049 ${LANG_SIMPCHINESE} "无法恢复先前的 32 位 TSF 注册。"
LangString L_050 ${LANG_ENGLISH} "Could not restore the previous 64-bit TSF module."
LangString L_050 ${LANG_SIMPCHINESE} "无法恢复先前的 64 位 TSF 模块。"
LangString L_051 ${LANG_ENGLISH} "Could not restore the previous 32-bit TSF module."
LangString L_051 ${LANG_SIMPCHINESE} "无法恢复先前的 32 位 TSF 模块。"
LangString L_052 ${LANG_ENGLISH} "Could not write the Zhiyi IME registry entries."
LangString L_052 ${LANG_SIMPCHINESE} "无法写入知意输入法安装注册表项。"
LangString L_053 ${LANG_ENGLISH} "Could not restore the previous Zhiyi IME registry state."
LangString L_053 ${LANG_SIMPCHINESE} "无法恢复先前的知意输入法注册表状态。"
LangString L_054 ${LANG_ENGLISH} "The Zhiyi IME rollback transaction was not found."
LangString L_054 ${LANG_SIMPCHINESE} "找不到知意输入法回滚事务。"
LangString L_055 ${LANG_ENGLISH} "Could not complete the Zhiyi IME installation."
LangString L_055 ${LANG_SIMPCHINESE} "无法完成知意输入法安装。"
LangString L_056 ${LANG_ENGLISH} "Zhiyi IME Settings"
LangString L_056 ${LANG_SIMPCHINESE} "知意输入法设置"
LangString L_057 ${LANG_ENGLISH} "Uninstall Zhiyi IME"
LangString L_057 ${LANG_SIMPCHINESE} "Uninstall 知意输入法"
LangString L_058 ${LANG_ENGLISH} "The previous Zhiyi IME version started a silent cleanup but could not hand over its registration. Run this installer again."
LangString L_058 ${LANG_SIMPCHINESE} "旧版知意输入法已开始静默清理，但无法完成注册状态交接。请重新运行此安装程序。"
LangString L_059 ${LANG_ENGLISH} "Could not uninstall the previous Zhiyi IME version automatically (result: $2). It was not replaced; uninstall it manually and try again."
LangString L_059 ${LANG_SIMPCHINESE} "无法自动卸载旧版知意输入法（结果：$2）。旧版本未被替换，请先手动卸载后重试。"
LangString L_060 ${LANG_ENGLISH} "Could not initialize the Zhiyi IME installer."
LangString L_060 ${LANG_SIMPCHINESE} "无法初始化知意输入法安装程序。"
LangString L_061 ${LANG_ENGLISH} "Another Zhiyi IME installer or uninstaller is running."
LangString L_061 ${LANG_SIMPCHINESE} "另一个知意输入法安装程序或卸载程序正在运行。"
LangString L_062 ${LANG_ENGLISH} "Zhiyi IME requires 64-bit Windows."
LangString L_062 ${LANG_SIMPCHINESE} "知意输入法需要 64 位 Windows。"
LangString L_063 ${LANG_ENGLISH} "An installation of Zhiyi IME that cannot be upgraded automatically was found. Uninstall it first, then run this installer."
LangString L_063 ${LANG_SIMPCHINESE} "检测到无法自动升级的知意输入法安装。请先卸载当前版本，再运行此安装程序。"
LangString L_064 ${LANG_ENGLISH} "Could not compare the installed version $InstalledVersion with version ${VERSION} of this installer."
LangString L_064 ${LANG_SIMPCHINESE} "无法比较已安装版本 $InstalledVersion 与安装包版本 ${VERSION}。"
LangString L_065 ${LANG_ENGLISH} "Zhiyi IME $InstalledVersion is installed. Continuing will downgrade it to ${VERSION}.$\r$\n$\r$\nContinue?"
LangString L_065 ${LANG_SIMPCHINESE} "当前已安装知意输入法 $InstalledVersion。继续将降级到 ${VERSION}。$\r$\n$\r$\n是否继续？"
LangString L_066 ${LANG_ENGLISH} "The Zhiyi IME downgrade was cancelled."
LangString L_066 ${LANG_SIMPCHINESE} "用户取消了知意输入法降级安装。"
LangString L_067 ${LANG_ENGLISH} "A silent installation does not downgrade from $InstalledVersion to ${VERSION} unless /ALLOWDOWNGRADE is given."
LangString L_067 ${LANG_SIMPCHINESE} "静默安装默认不允许从 $InstalledVersion 降级到 ${VERSION}。请显式使用 /ALLOWDOWNGRADE。"
LangString L_068 ${LANG_ENGLISH} "Could not initialize the Zhiyi IME uninstaller."
LangString L_068 ${LANG_SIMPCHINESE} "无法初始化知意输入法卸载程序。"
LangString L_069 ${LANG_ENGLISH} "Hide details"
LangString L_069 ${LANG_SIMPCHINESE} "收起占用详情"
LangString L_070 ${LANG_ENGLISH} "Show details"
LangString L_070 ${LANG_SIMPCHINESE} "查看占用详情"
LangString L_071 ${LANG_ENGLISH} "Some applications still use the previous version; part of the update takes effect after Windows restarts."
LangString L_071 ${LANG_SIMPCHINESE} "部分应用仍使用上一版本；部分更新将在下次 Windows 重启后生效。"
LangString L_072 ${LANG_ENGLISH} "Some running applications still use the previous version; reopen them to switch."
LangString L_072 ${LANG_SIMPCHINESE} "部分正在运行的应用仍使用上一版本，重新打开后即可切换。"
LangString L_073 ${LANG_ENGLISH} "Part of the update takes effect after Windows restarts."
LangString L_073 ${LANG_SIMPCHINESE} "部分更新将在下次 Windows 重启后生效。"
LangString L_074 ${LANG_ENGLISH} "Uninstall Zhiyi IME"
LangString L_074 ${LANG_SIMPCHINESE} "卸载知意输入法"
LangString L_075 ${LANG_ENGLISH} "Remove the program, and choose whether to delete your personal data as well."
LangString L_075 ${LANG_SIMPCHINESE} "移除程序，并选择是否同时删除个人数据。"
LangString L_076 ${LANG_ENGLISH} "Zhiyi IME will be removed. Program files still in use are removed automatically after Windows restarts."
LangString L_076 ${LANG_SIMPCHINESE} "知意输入法将从系统中移除。正在使用的程序文件会自动在 Windows 重启后删除。"
LangString L_077 ${LANG_ENGLISH} "Your settings and dictionary are kept by default and are used again if you reinstall."
LangString L_077 ${LANG_SIMPCHINESE} "用户配置和词库默认保留，之后重新安装仍可继续使用。"
LangString L_078 ${LANG_ENGLISH} "Delete my settings and dictionary data"
LangString L_078 ${LANG_SIMPCHINESE} "删除用户配置和词库数据"
LangString L_079 ${LANG_ENGLISH} "Your personal data will be deleted permanently. This cannot be undone."
LangString L_079 ${LANG_SIMPCHINESE} "勾选后个人数据将永久删除，无法撤销。"
LangString L_080 ${LANG_ENGLISH} "Uninstall"
LangString L_080 ${LANG_SIMPCHINESE} "卸载"
LangString L_081 ${LANG_ENGLISH} "Zhiyi IME has been removed, but some program files could not be cleaned up. Running the installer again will retry."
LangString L_081 ${LANG_SIMPCHINESE} "知意输入法已从系统中移除，但部分程序文件未能自动清理。重新运行安装程序时会再次处理。"
LangString L_082 ${LANG_ENGLISH} "The selected folder is not empty and is not a Zhiyi IME installation folder. Choose an empty folder."
LangString L_082 ${LANG_SIMPCHINESE} "所选目录不为空，并且不是知意输入法安装目录。请选择一个空目录。"
LangString L_083 ${LANG_ENGLISH} "The selected folder contains files that do not belong to Zhiyi IME. Choose another folder."
LangString L_083 ${LANG_SIMPCHINESE} "所选产品目录包含不属于知意输入法的文件。请选择其他目录。"
LangString L_084 ${LANG_ENGLISH} "Could not safely prepare the Zhiyi IME folder: $InstallBaseDir$\r$\nChoose a new or empty folder (not a symbolic link or a network location)."
LangString L_084 ${LANG_SIMPCHINESE} "无法安全地准备知意输入法产品目录：$InstallBaseDir$\r$\n请选择一个新的或空的文件夹（不能是符号链接或网络位置）。"
LangString L_085 ${LANG_ENGLISH} "Could not prepare the Zhiyi IME version lifecycle state."
LangString L_085 ${LANG_SIMPCHINESE} "无法准备知意输入法版本生命周期状态。"
LangString L_086 ${LANG_ENGLISH} "The Zhiyi IME lifecycle state has no valid installation target."
LangString L_086 ${LANG_SIMPCHINESE} "知意输入法生命周期状态缺少有效的安装目标。"
LangString L_087 ${LANG_ENGLISH} "Could not read the Zhiyi IME transaction folder."
LangString L_087 ${LANG_SIMPCHINESE} "无法读取知意输入法安装事务目录。"
LangString L_088 ${LANG_ENGLISH} "The Zhiyi IME transaction folder is in an invalid state."
LangString L_088 ${LANG_SIMPCHINESE} "知意输入法安装事务目录状态无效。"
LangString L_089 ${LANG_ENGLISH} "Could not commit the Zhiyi IME version lifecycle state."
LangString L_089 ${LANG_SIMPCHINESE} "无法提交知意输入法版本生命周期状态。"
LangString L_090 ${LANG_ENGLISH} "Could not remove retired versions; the next installation will retry."
LangString L_090 ${LANG_SIMPCHINESE} "无法清理退役版本，后续安装将再次处理。"
LangString L_091 ${LANG_ENGLISH} "Could not finish cleaning up program files; the next installation will retry."
LangString L_091 ${LANG_SIMPCHINESE} "无法完成程序文件清理；后续安装将再次处理残留文件。"
LangString L_092 ${LANG_ENGLISH} "Could not read the cleanup result; the next installation will retry."
LangString L_092 ${LANG_SIMPCHINESE} "无法读取程序文件清理结果；后续安装将再次处理残留文件。"
LangString L_093 ${LANG_ENGLISH} "Could not verify the Zhiyi IME file list. Nothing was uninstalled; reinstall, then uninstall."
LangString L_093 ${LANG_SIMPCHINESE} "无法验证知意输入法程序文件清单。卸载未进行，请重新安装后再卸载。"
LangString L_094 ${LANG_ENGLISH} "Could not restore the 64-bit TSF registration."
LangString L_094 ${LANG_SIMPCHINESE} "无法恢复 64 位 TSF 注册。"
LangString L_095 ${LANG_ENGLISH} "Could not restore the 32-bit TSF registration."
LangString L_095 ${LANG_SIMPCHINESE} "无法恢复 32 位 TSF 注册。"
LangString L_096 ${LANG_ENGLISH} "Could not restore the 64-bit TSF module."
LangString L_096 ${LANG_SIMPCHINESE} "无法恢复 64 位 TSF 模块。"
LangString L_097 ${LANG_ENGLISH} "Could not restore the 32-bit TSF module."
LangString L_097 ${LANG_SIMPCHINESE} "无法恢复 32 位 TSF 模块。"
LangString L_098 ${LANG_ENGLISH} "$FailureMessage$\r$\n$\r$\nThe Zhiyi IME service could not be restarted."
LangString L_098 ${LANG_SIMPCHINESE} "$FailureMessage$\r$\n$\r$\n知意输入法后台恢复启动失败。"
LangString L_099 ${LANG_ENGLISH} "The previous Zhiyi IME uninstallation transaction is incomplete or invalid."
LangString L_099 ${LANG_SIMPCHINESE} "先前的知意输入法卸载事务不完整或无效。"
LangString L_100 ${LANG_ENGLISH} "Could not write the Zhiyi IME uninstallation transaction."
LangString L_100 ${LANG_SIMPCHINESE} "无法写入知意输入法卸载事务。"
LangString L_101 ${LANG_ENGLISH} "Could not commit the Zhiyi IME uninstallation transaction (Win32 error $1)."
LangString L_101 ${LANG_SIMPCHINESE} "无法提交知意输入法卸载事务（Win32 错误 $1）。"
LangString L_102 ${LANG_ENGLISH} "The Zhiyi IME installation is not complete. Run the installer again before uninstalling."
LangString L_102 ${LANG_SIMPCHINESE} "知意输入法安装尚未完成。请重新运行安装程序后再卸载。"
LangString L_103 ${LANG_ENGLISH} "Could not record the legacy IME removal state."
LangString L_103 ${LANG_SIMPCHINESE} "无法记录传统 IME 删除状态。"
LangString L_104 ${LANG_ENGLISH} "Could not unregister the 32-bit TSF module."
LangString L_104 ${LANG_SIMPCHINESE} "无法注销 32 位 TSF 模块。"
LangString L_105 ${LANG_ENGLISH} "Could not unregister the 64-bit TSF module."
LangString L_105 ${LANG_SIMPCHINESE} "无法注销 64 位 TSF 模块。"
LangString L_106 ${LANG_ENGLISH} "The registered 32-bit TSF module is missing."
LangString L_106 ${LANG_SIMPCHINESE} "缺少已注册的 32 位 TSF 模块。"
LangString L_107 ${LANG_ENGLISH} "The registered 64-bit TSF module is missing."
LangString L_107 ${LANG_SIMPCHINESE} "缺少已注册的 64 位 TSF 模块。"
LangString L_108 ${LANG_ENGLISH} "Could not schedule the legacy IME file cleanup; the next installation will retry."
LangString L_108 ${LANG_SIMPCHINESE} "无法登记传统 IME 文件清理，将在后续安装时重试。"
