"""Generate engine/src/syllable_frequency.h from the pinyin dictionary.

  python scripts/gen_syllable_frequency.py [--input data/pinyin.dict.db.zip]

For every syllable, the natural log of its share of all syllable occurrences in the dictionary
(each word's frequency counted once per syllable it contains). The syllabifier uses it to
enumerate the plausible readings of an initial first (g -> gong, guo, ge before ga, gai).
"""
import argparse
import math
import os
import sqlite3
import tempfile
import zipfile
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "..", "engine", "src", "syllable_frequency.h")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=os.path.join(HERE, "..", "data", "pinyin.dict.db.zip"))
    parser.add_argument("--output", default=OUTPUT)
    args = parser.parse_args()

    db_path = args.input
    temp_dir = None
    if db_path.endswith(".zip"):
        temp_dir = tempfile.mkdtemp()
        with zipfile.ZipFile(db_path) as archive:
            name = [n for n in archive.namelist() if n.endswith(".db")][0]
            db_path = archive.extract(name, temp_dir)

    totals = Counter()
    conn = sqlite3.connect(db_path)
    for frequency, syllable_ids in conn.execute("SELECT frequency, syllable_ids FROM dict"):
        if not syllable_ids:
            continue
        for syllable in syllable_ids.split(":"):
            if syllable and syllable.isalpha():
                totals[syllable] += max(frequency, 0)
    conn.close()

    total = sum(totals.values())
    rows = sorted(totals.items())
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Copyright (c) 2026 Zhiyi IME Contributors. GPL-3.0-only.\n")
        f.write("// Generated by scripts/gen_syllable_frequency.py from the pinyin dictionary: ln of each\n")
        f.write("// syllable's share of all syllable occurrences (word frequency counted per syllable).\n")
        f.write("// Sorted by syllable for binary search.\n")
        f.write("#ifndef CXXIME_SYLLABLE_FREQUENCY_H_\n#define CXXIME_SYLLABLE_FREQUENCY_H_\n\n")
        f.write("#include <string_view>\n\nnamespace cxxime {\n\n")
        f.write("struct SyllableFrequency {\n    std::string_view syllable;\n    float log_share;\n};\n\n")
        f.write(f"inline constexpr SyllableFrequency kSyllableFrequencies[{len(rows)}] = {{\n")
        for syllable, count in rows:
            log_share = math.log((count + 1) / total)
            f.write(f'    {{"{syllable}", {log_share:.4f}f}},\n')
        f.write("};\n\n}  // namespace cxxime\n\n#endif  // CXXIME_SYLLABLE_FREQUENCY_H_\n")
    print(f"{len(rows)} syllables -> {os.path.relpath(args.output)}")


if __name__ == "__main__":
    main()
