#!/usr/bin/env python3
# Copyright (c) 2026 Zhiyi IME Contributors. GPL-3.0-only.
"""Signing key and update manifest for Settings > Updates (update/include/cxxime/update.h).

  genkey     create the private key (once, on the release machine) and write its public key
             into update/src/update_public_key.inc
  pubkey     write the public key of an existing private key into update_public_key.inc
  manifest   write latest.json and latest.json.sig for an installer (package.py calls this)

The private key (default %USERPROFILE%\\.zhiyi-release\\update-signing.pem, or the
ZHIYI_UPDATE_KEY variable) must never be committed: whoever holds it can ship updates. Keep a
backup; without it, users can only move to a new key by installing a release by hand.
"""

from __future__ import annotations

import argparse
import base64
import datetime
import hashlib
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC_KEY_INC = ROOT / "update" / "src" / "update_public_key.inc"
DOWNLOAD_PREFIX = "https://github.com/dd1000001000/zhiyi_ime/releases/download/"
LANGUAGES = ("zh-CN", "en-US")


def default_key_path() -> Path:
    configured = os.environ.get("ZHIYI_UPDATE_KEY")
    if configured:
        return Path(configured)
    return Path.home() / ".zhiyi-release" / "update-signing.pem"


def crypto():
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec, utils
    except ImportError:  # pragma: no cover - reported to the release manager
        sys.exit("update_signing.py needs the Python 'cryptography' package")
    return hashes, serialization, ec, utils


def load_private_key(path: Path):
    _, serialization, _, _ = crypto()
    if not path.is_file():
        raise SystemExit(f"no update signing key at {path} (run: update_signing.py genkey)")
    return serialization.load_pem_private_key(path.read_bytes(), password=None)


def public_key_base64(private_key) -> str:
    numbers = private_key.public_key().public_numbers()
    raw = numbers.x.to_bytes(32, "big") + numbers.y.to_bytes(32, "big")
    return base64.b64encode(raw).decode("ascii")


def write_public_key_inc(private_key) -> None:
    PUBLIC_KEY_INC.write_text(
        "// Generated by scripts/update_signing.py: the public half of the update signing key\n"
        "// (ECDSA P-256, X || Y, base64). Replace only together with a release installed by hand.\n"
        f'"{public_key_base64(private_key)}"\n',
        encoding="utf-8",
        newline="\r\n",
    )
    print(f"public key written to {PUBLIC_KEY_INC.relative_to(ROOT)}")


def sign(private_key, data: bytes) -> str:
    hashes, _, ec, utils = crypto()
    der = private_key.sign(data, ec.ECDSA(hashes.SHA256()))
    r, s = utils.decode_dss_signature(der)
    return base64.b64encode(r.to_bytes(32, "big") + s.to_bytes(32, "big")).decode("ascii")


def verify(private_key, data: bytes, signature: str) -> None:
    hashes, _, ec, utils = crypto()
    raw = base64.b64decode(signature)
    der = utils.encode_dss_signature(int.from_bytes(raw[:32], "big"), int.from_bytes(raw[32:], "big"))
    private_key.public_key().verify(der, data, ec.ECDSA(hashes.SHA256()))


def genkey(args) -> int:
    _, serialization, ec, _ = crypto()
    path = Path(args.key)
    if path.exists():
        raise SystemExit(f"{path} already exists; not overwritten")
    path.parent.mkdir(parents=True, exist_ok=True)
    private_key = ec.generate_private_key(ec.SECP256R1())
    path.write_bytes(private_key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ))
    print(f"private key written to {path} (back it up; never commit it)")
    write_public_key_inc(private_key)
    return 0


def pubkey(args) -> int:
    write_public_key_inc(load_private_key(Path(args.key)))
    return 0


def read_notes(version: str, directory: Path) -> dict[str, str]:
    """docs/release-notes/<version>.<language>.md, when present."""
    notes = {}
    for language in LANGUAGES:
        path = directory / f"{version}.{language}.md"
        if path.is_file():
            notes[language] = path.read_text(encoding="utf-8").strip()
    return notes


def build_manifest(installer: Path, version: str, base: str, notes: dict[str, str]) -> bytes:
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?", version):
        raise SystemExit(f"invalid version {version!r}")
    digest = hashlib.sha256()
    with installer.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    manifest = {
        "version": version,
        "file": installer.name,
        "url": f"{base}v{version}/{installer.name}",
        "size": installer.stat().st_size,
        "sha256": digest.hexdigest(),
        "published": datetime.date.today().isoformat(),
        "notes": notes,
    }
    return (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def write_manifest(installer: Path, version: str, out: Path, key: Path,
                   base: str = DOWNLOAD_PREFIX, notes: dict[str, str] | None = None) -> Path:
    private_key = load_private_key(key)
    if notes is None:
        notes = read_notes(version, ROOT / "docs" / "release-notes")
    data = build_manifest(installer, version, base, notes)
    signature = sign(private_key, data)
    verify(private_key, data, signature)
    out.mkdir(parents=True, exist_ok=True)
    manifest_path = out / "latest.json"
    manifest_path.write_bytes(data)
    (out / "latest.json.sig").write_text(signature + "\n", encoding="ascii")
    return manifest_path


def manifest(args) -> int:
    path = write_manifest(Path(args.installer), args.version, Path(args.out), Path(args.key),
                          args.base)
    print(f"wrote {path} and {path.name}.sig")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--key", default=str(default_key_path()), help="private key (PEM)")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("genkey").set_defaults(run=genkey)
    commands.add_parser("pubkey").set_defaults(run=pubkey)
    manifest_parser = commands.add_parser("manifest")
    manifest_parser.add_argument("--installer", required=True)
    manifest_parser.add_argument("--version", required=True)
    manifest_parser.add_argument("--out", required=True)
    manifest_parser.add_argument("--base", default=DOWNLOAD_PREFIX,
                                 help="URL the release folders v<version>/ are under")
    manifest_parser.set_defaults(run=manifest)
    args = parser.parse_args()
    return args.run(args)


if __name__ == "__main__":
    sys.exit(main())
