#!/usr/bin/env python3
"""Generate compact runtime ranges from the frozen offline Unicode policy."""

import argparse
import json
from pathlib import Path


def generate(source, output):
    data = json.loads(Path(source).read_text(encoding="utf-8"))
    if data["schema"] != 1 or data["unicode_version"] != "17.0":
        raise ValueError("unsupported Unicode classification data")
    lines = [
        "// Generated by data/tools/generate_symbol_ranges.py; do not edit.",
        "// Unicode 17.0 P/S + non-digit Emoji; see THIRD_PARTY_NOTICES.txt.",
        "",
        "namespace {",
        "",
        "struct SymbolRange {",
        "    std::uint32_t first;",
        "    std::uint32_t last;",
        "};",
        "",
        "constexpr SymbolRange kSymbolRanges[] = {",
    ]
    points = set()
    for prop in ("Punctuation_Or_Symbol", "Emoji"):
        previous = -1
        for value in data["properties"][prop]:
            bounds = value.split("..")
            first, last = int(bounds[0], 16), int(bounds[-1], 16)
            if not previous < first <= last <= 0x10FFFF:
                raise ValueError("invalid or unsorted symbol range")
            points.update(range(first, last + 1))
            previous = last
    points.difference_update(range(ord("0"), ord("9") + 1))
    ranges = []
    for point in sorted(points):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    for first, last in ranges:
        lines.append(f"    {{0x{first:04X}, 0x{last:04X}}},")
    lines.extend(["};", "", "} // namespace", ""])
    with Path(output).open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    generate(args.source, args.output)
